import jsPDF from "jspdf";
import type { CheckResult } from "./types";

const MARGIN = 48;

/**
 * Builds the PDF report described in the plan: header, score summary,
 * per-source breakdown, full text with color-coded sentences, and a
 * disclaimer footer on every page.
 */
export function generatePdfReport(result: CheckResult): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  const ensureSpace = (lineHeight: number) => {
    if (y + lineHeight > pageHeight - MARGIN - 20) {
      doc.addPage();
      y = MARGIN;
    }
  };

  // --- Header ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text("Plagiarism Check Report", MARGIN, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Generated: ${dateStr}  ·  Tool: PlagCheck by ERS`, MARGIN, y);
  y += 20;

  doc.setDrawColor(226, 232, 240);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 24;

  // --- Score summary ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`Originality Score: ${result.originalityScore}%`, MARGIN, y);
  y += 14;

  const [r, g, b] = scoreColor(result.originalityScore);
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(MARGIN, y, contentWidth, 8, 4, 4, "F");
  doc.setFillColor(r, g, b);
  doc.roundedRect(MARGIN, y, (contentWidth * Math.min(result.originalityScore, 100)) / 100, 8, 4, 4, "F");
  y += 26;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const summaryLines = [
    `Total words: ${result.totalWords}`,
    `Sentences checked: ${result.sentenceCount} (${result.sentencesChecked} searched)`,
    `Original: ${result.breakdown.originalPercent}%   Paraphrased: ${result.breakdown.paraphrasedPercent}%   Matched: ${result.breakdown.matchedPercent}%`,
  ];
  for (const line of summaryLines) {
    ensureSpace(14);
    doc.text(line, MARGIN, y);
    y += 14;
  }
  y += 12;

  // --- Matched sources ---
  ensureSpace(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Matched Sources", MARGIN, y);
  y += 18;

  if (result.sources.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(22, 163, 74);
    ensureSpace(16);
    doc.text("No matching sources found — looks original.", MARGIN, y);
    y += 20;
  } else {
    doc.setFontSize(9.5);
    result.sources.forEach((s, i) => {
      ensureSpace(28);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      const label = doc.splitTextToSize(`${i + 1}. ${s.title || s.url}`, contentWidth - 70)[0];
      doc.text(label, MARGIN, y);
      doc.setTextColor(148, 163, 184);
      doc.text(`${s.matchPercent.toFixed(1)}%`, pageWidth - MARGIN - 40, y);
      y += 13;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(truncate(s.url, 90), MARGIN, y);
      doc.setFontSize(9.5);
      y += 15;
    });
  }
  y += 10;

  ensureSpace(20);
  doc.setDrawColor(226, 232, 240);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 22;

  // --- Full text with color-coded sentences ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  ensureSpace(18);
  doc.text("Detailed Results", MARGIN, y);
  y += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  const lineHeight = 13;
  for (const sentence of result.sentences) {
    const [cr, cg, cb] = classificationColor(sentence.classification);
    doc.setTextColor(cr, cg, cb);
    const wrapped = doc.splitTextToSize(sentence.original, contentWidth);
    for (const line of wrapped) {
      ensureSpace(lineHeight);
      doc.text(line, MARGIN, y);
      y += lineHeight;
    }
    y += 3;
  }

  // --- Footer on every page ---
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "This report was generated by PlagCheck. Results are indicative, not definitive.",
      MARGIN,
      pageHeight - 24
    );
    doc.text(`Page ${p} of ${pageCount}`, pageWidth - MARGIN - 55, pageHeight - 24);
  }

  return doc;
}

function scoreColor(score: number): [number, number, number] {
  if (score >= 80) return [34, 197, 94];
  if (score >= 60) return [245, 158, 11];
  return [239, 68, 68];
}

function classificationColor(
  classification: CheckResult["sentences"][number]["classification"]
): [number, number, number] {
  if (classification === "matched") return [220, 38, 38];
  if (classification === "paraphrased") return [180, 83, 9];
  return [51, 65, 85];
}

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}
